<?php

use Illuminate\Database\Seeder;
use App\Product;
use App\Restaurant;
class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
            $products = [
            [
                'name' => 'Tasty fries',
                'ingredients' => 'Patatine fritte , bacon grigliato , salsa Cheddar , salsa OWW',
                'description' => 'Patate* Premium fries ricoperte da mix di formaggi, salsa Cheddar e bacon grigliato, servite con salsa OWW',
                'type' => 'Antipasto',
                'price' => 4.50,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Gringos nachos',
                'ingredients' => 'Triangoli di mais , salsa messicana , salsa Guacamole , Peri Cheddar',
                'description' => 'Triangolini di mais con salse tipiche messicane (Guacamole homemade, salsa Messicana e Peri Cheddar)',
                'type' => 'Antipasto',
                'price' => 4.5,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Onion rings',
                'ingredients' => 'Anelli di cipolla , salsa Barbecue',
                'description' => 'Anelli di cipolla* pastellati e fritti, serviti con salsa Barbecue (8 pezzi)',
                'type' => 'Antipasto',
                'price' => 5,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Mozzarella Sticks',
                'ingredients' => 'Mozzarella , salsa OWW',
                'description' => 'Bastoncini* di mozzarella pastellati e fritti serviti con salsa OWW (6 pezzi) ',
                'type' => 'Antipasto',
                'price' => 5,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Chicken Wings',
                'ingredients' => 'Pollo , peperoncino, salsa OWW',
                'description' => 'Alette di pollo* fritte particolarmente speziate, leggermente piccanti e servite con salsa OWW (8 pezzi)',
                'type' => 'Antipasto',
                'price' => 9,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Chicken Nuggets',
                'ingredients' => 'Pollo , mais, salsa OWW',
                'description' => 'Bocconcini di pollo fritti, ricoperti di fiocchi di mais tostati, serviti con salsa OWW (8 pezzi)',
                'type' => 'Antipasto',
                'price' => 8,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Green Balls',
                'ingredients' => 'Olive verdi , patate, scamorza affumicata, salsa OWW',
                'description' => 'Olive verdi panate, farcite con patata e scamorza affumicata, servite con salsa Old Wild West (6 pezzi)',
                'type' => 'Antipasto',
                'price' => 4,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Apache',
                'ingredients' => 'Pane , Hamburger, pomodoro, cetriolini, cipolla',
                'description' => 'Pane, hamburger*, cipolla bianca, pomodoro e cetriolini, servito con patate* French Fries',
                'type' => 'Primo',
                'price' => 8,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Navajo',
                'ingredients' => 'Pane , Hamburger, formaggio Cheddar, cetriolini',
                'description' => 'Pane, hamburger, formaggio Cheddar, servito con patate* French Fries',
                'type' => 'Primo',
                'price' => 8.5,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Dakota',
                'ingredients' => 'Pane , Hamburger, formaggio Cheddar, bacon grigliato',
                'description' => 'Pane, hamburger*, formaggio fuso e bacon grigliato, servito con patate* French Fries',
                'type' => 'Primo',
                'price' => 9,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Nuvola Rossa',
                'ingredients' => 'Pane , Hamburger, formaggio Cheddar, bacon grigliato, cipolla bianca',
                'description' => 'Pane, hamburger*, formaggio fuso, bacon grigliato e julienne di cipolla bianca arrostita, servito con patate* French Fries',
                'type' => 'Primo',
                'price' => 9.5,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'BBQ Burger',
                'ingredients' => 'Pane , Hamburger, Onion rings, bacon grigliato, lattuga, salsa Barbecue',
                'description' => 'Pane, hamburger*, bacon grigliato, Onion Rings*, lattuga e salsa Barbecue, servito con patate* Premium Fries e salsa Barbecue',
                'type' => 'Primo',
                'price' => 10,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Toro Seduto',
                'ingredients' => 'Pane , Hamburger, formaggio Cheddar, bacon grigliato, cipolla bianca',
                'description' => 'Pane, 2 hamburger*, formaggio fuso, bacon grigliato, servito con patate* Premium Fries e cipolla bianca',
                'type' => 'Primo',
                'price' => 10,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Galletto Old Wild West',
                'ingredients' => 'Galletto , pane, salsa OWW',
                'description' => 'Galletto Italiano alla griglia, accuratamente speziato, servito con patate French Fries, salsa OWW e un crostino di pane',
                'type' => 'Secondo',
                'price' => 12,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'BBQ Ribs',
                'ingredients' => 'Costine di maiale , salsa Barbecue',
                'description' => 'Costine di maiale cotte in sottovuoto con salsa Barbecue servite con patate* Premium Fries e salsa Barbecue - 1/2 baffa',
                'type' => 'Secondo',
                'price' => 11.5,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Grigliata Generale Custer',
                'ingredients' => 'Manzo Argentino , petto di pollo, salsiccia, wurstel, verdure, salsa OWW',
                'description' => '(minimo 2 persone) Manzo Argentino di prima scelta, petto di pollo*, salsiccia, wurstel e verdure alla griglia, accompagnati da patate* Premium Fries e salsa OWW',
                'type' => 'Secondo',
                'price' => 15,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Norwegian Grill',
                'ingredients' => 'Trancio di salmone , rucola, spinaci, parmiggiano Reggiano DOP, salsa Philadelphia',
                'description' => 'Trancio di salmone* al forno su letto di rucola servito con spinaci* conditi con burro e Parmigiano Reggiano DOP e salsa con Philadelphia (cetriolini, maionese senapata, erba cipollina e Philadelphia), accompagnato da patate al forno e salsa OWW',
                'type' => 'Secondo',
                'price' => 13,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'American Pancake',
                'ingredients' => 'Pancake, frutti di bosco, sciroppo, zucchero, panna',
                'description' => 'Due soffici pancakes* ricoperti da frutti di bosco* in salsa, sciroppo, panna montata e zucchero a velo',
                'type' => 'Dolce',
                'price' => 5,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Suffle Due Lune',
                'ingredients' => 'Suffle al cioccolato, gelato, granella di nocciole, topping',
                'description' => 'Souffle al cioccolato, gelato al fiordilatte, cioccolato croccante, topping al cioccolato e granella di nocciole',
                'type' => 'Dolce',
                'price' => 5,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Cheesecake',
                'ingredients' => 'Cheesecake, frutti di bosco, granella di nocciole, topping',
                'description' => 'Cremosa Cheesecake, servita con frutti di bosco in salsa, gelato al fiordilatte, cornachos (tortillas di grano dorate) e zucchero a velo',
                'type' => 'Dolce',
                'price' => 5,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Coppa Alaska',
                'ingredients' => 'Gelato, Nutella®, cioccolato croccante, panna',
                'description' => 'Gelato al fiordilatte con Nutella®, cioccolato croccante, panna montata, topping al cioccolato e granella di nocciole',
                'type' => 'Dolce',
                'price' => 5,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Sweet Forest',
                'ingredients' => 'Gelato, frutti di bosco, nocciola, panna',
                'description' => 'Gelato al fiordilatte e nocciola con frutti di bosco in salsa e panna montata',
                'type' => 'Dolce',
                'price' => 5,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Coppetta Oreo',
                'ingredients' => 'Gelato, crema di nocciole, biscotti Oreo, panna, topping',
                'description' => 'Gelato al fiordilatte con crema di nocciole, crumble di biscotti Oreo®, panna montata, granella di nocciole, topping al cioccolato e biscotto Oreo®',
                'type' => 'Dolce',
                'price' => 5,
                'availability'  => true,
                'restaurant_id' => 1,
            ],
            [
                'name' => 'Anelli della regina',
                'ingredients' => 'Cipolla, salsa Barbecue',
                'description' => 'Anelli di cipolla pastellati fritti serviti con salsa Barbecue',
                'type' => 'Antipasto',
                'price' => 5,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Crocchette del viandante',
                'ingredients' => 'Patate, mozzarella, salsa Arthur',
                'description' => 'Crocchette di patate con mozzarella e salsa Arthur(6 pezzi)',
                'type' => 'Antipasto',
                'price' => 5,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Bastoncini del monaco',
                'ingredients' => 'Mozzarella',
                'description' => 'Bastoncini di mozzarella panati(6 pezzi)',
                'type' => 'Antipasto',
                'price' => 5,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Bocconcini del re',
                'ingredients' => 'Pollo, mais, salsa Arthur',
                'description' => 'Bocconcini di pollo fritti, ricoperti di mais tostati, serviti con salsa Arthur(5 pezzi)',
                'type' => 'Antipasto',
                'price' => 6,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Alette di Arthur',
                'ingredients' => 'Pollo, peperoncino, salsa Arthur',
                'description' => 'Alette di pollo fritte, particolarmente speziate, leggermente piccanti, servite con salsa Arthur(8 pezzi)',
                'type' => 'Antipasto',
                'price' => 8,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Lionel',
                'ingredients' => 'Pane, cipolla, hamburger, pomodoro, cetriolini',
                'description' => 'Hamburger con cipolla, pomodoro fresco e cetriolini',
                'type' => 'Primo',
                'price' => 7,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Fergus',
                'ingredients' => 'Pane, hamburger, formaggio fuso',
                'description' => 'Hamburger con formaggio fuso',
                'type' => 'Primo',
                'price' => 7.5,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Lancelot',
                'ingredients' => 'Pane, hamburger, bacon grigliato, formaggio fuso',
                'description' => 'Hamburger con bacon grigliato e formaggio fuso',
                'type' => 'Primo',
                'price' => 8,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Balor',
                'ingredients' => 'Pane, hamburger, bacon grigliato, formaggio fuso, peperoni',
                'description' => 'Hamburger con bacon grigliato, julienne di peperoni arrostiti e formaggio fuso',
                'type' => 'Primo',
                'price' => 9,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Tor',
                'ingredients' => 'Pane, hamburger, bacon grigliato, formaggio fuso, cipolla',
                'description' => 'Doppio hamburger, bacon grigliato, formaggio fuso e cipolla',
                'type' => 'Primo',
                'price' => 10,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Sir Escalot',
                'ingredients' => 'Maiale',
                'description' => 'Cotoletta di maiale',
                'type' => 'Secondo',
                'price' => 9,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Sir Dinadan',
                'ingredients' => 'Maiale, prosciutto cotto, formaggio Montasio',
                'description' => 'Cotoletta di maiale panata farcita con prosciutto cotto e formaggio Montasio',
                'type' => 'Secondo',
                'price' => 11.5,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Sir Lamorak',
                'ingredients' => 'Manzo, salsa Arthur',
                'description' => 'Entrecote di manzo di prima scelta alla griglia, servita con patate reali e salsa Arthur',
                'type' => 'Secondo',
                'price' => 14.5,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Sir Gaheris',
                'ingredients' => 'Manzo, rucola, salsa Barbecue',
                'description' => 'Tagliata di filetto di manzo alla griglia su letto di rucola, accompagnata da patate reali e salsa Barbecue',
                'type' => 'Secondo',
                'price' => 17,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Sir Cador',
                'ingredients' => 'Manzo, verdure, salsa Arthur',
                'description' => 'Controfiletto di manzo alla griglia accompagnato da patate reali, caponata di verdure e salsa Arthur',
                'type' => 'Secondo',
                'price' => 16,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Lunetta',
                'ingredients' => 'Pasta frolla, formaggio dolce, ciocciolato, panna',
                'description' => 'Torta di pasta frolla e formaggio dolce, servita con topping al cioccolato e panna montata',
                'type' => 'Dolce',
                'price' => 4.5,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Freccia Nera',
                'ingredients' => 'Souffle al cioccolato, panna',
                'description' => 'Souffle al cioccolato servito con topping al cioccolato e panna montata',
                'type' => 'Dolce',
                'price' => 5,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Coppa Graal',
                'ingredients' => 'Gelato, Nutella, nocciola, panna, crema al cioccolato',
                'description' => 'Gelato al fior di latte e Nutella®, con granella di nocciola, panna montata e crema al cioccolato',
                'type' => 'Dolce',
                'price' => 5,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Dolce Incantesimo',
                'ingredients' => 'Crema, vaniglia, zucchero di canna',
                'description' => 'Crema profumata alla vaniglia, ricoperta di zucchero di canna caramellato',
                'type' => 'Dolce',
                'price' => 5,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Scrigno Incantato',
                'ingredients' => 'Crepes, Nutella, granella di nocciola, crema, gelato',
                'description' => 'Crepes con Nutella®, granella di nocciola, crema al cioccolato e gelato al fior di latte',
                'type' => 'Dolce',
                'price' => 5.5,
                'availability'  => true,
                'restaurant_id' => 2,
            ],
            [
                'name' => 'Involtini Primavera',
                'ingredients' => 'Sfoglia, carote, cavolo Cappuccio, cipolle bianche, verza',
                'description' => 'Sfoglia per involtini farcita con carote, cavolo cappuccio, cipolle bianche e verza(2 pezzi)',
                'type' => 'Antipasto',
                'price' => 1.5,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Ravioli al vapore',
                'ingredients' => 'Farina , maiale , cipolla bianca , cavolo Cappuccio, salsa di soia ',
                'description' => 'Ravioli di maiale, arricchiti con cavolo cappuccio, cipolla bianca, cavolo cappuccio, condito con salsa di soia e cotto al vapore(4 pezzi)',
                'type' => 'Antipasto',
                'price' => 3,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Usuzukuri',
                'ingredients' => 'Pesce , salsa Ponzu',
                'description' => 'Carpaccio crudo di pesce misto, arricchito con salsa Ponzu',
                'type' => 'Antipasto',
                'price' => 12,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Kushi Sake',
                'ingredients' => 'Salmone , salsa Ponzu',
                'description' => 'Salmone crudo abattuto, arricchito con salsa Ponzu',
                'type' => 'Antipasto',
                'price' => 15,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Nuvolette di drago',
                'ingredients' => 'Gamberetti , fecola di Tapioca, olio di arachidi',
                'description' => 'Nuvolette di gamberi, fritte con olio di arachidi',
                'type' => 'Antipasto',
                'price' => 3,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Riso alla cantonese',
                'ingredients' => 'Riso Ribe , prosciutto cotto, pisellini, uova, erba cipollina',
                'description' => 'Riso cinese saltato in padella, condito con dadi di prosciutto cotto, pisellini, erba cipollina e uova',
                'type' => 'Primo',
                'price' => 5,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Spaghetti di soia',
                'ingredients' => 'Spaghetti, soia , carote, cipolle bianca, zucchine, peperoni',
                'description' => 'Spaghetti di soia, conditi con salsa di soia e arricchiti con carote, cipolle bianche, peperoni e zucchine grigliate',
                'type' => 'Primo',
                'price' => 5,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Uramaki Sake',
                'ingredients' => 'Riso, salmone , philadelphia, avocado',
                'description' => 'Rotoli di sushi farciti con salmone, philadelphia e avocado(3 pezzi)',
                'type' => 'Primo',
                'price' => 10,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Uramaki Tuna',
                'ingredients' => 'Riso, tonno , philadelphia, avocado',
                'description' => 'Rotoli di sushi farciti con tonno, philadelphia e avocado(3 pezzi)',
                'type' => 'Primo',
                'price' => 10,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Uramaki Spicy Rainbow',
                'ingredients' => 'Riso, pesce misto , philadelphia, avocado, peperoncino',
                'description' => 'Rotoli di sushi piccanti farciti con pesce misto, philadelphia e avocado(3 pezzi)',
                'type' => 'Primo',
                'price' => 13,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Pollo alle mandorle',
                'ingredients' => 'Petto di pollo, mandorle , germogli di bambu, salsa di soia',
                'description' => 'Bocconcini di pollo arricchiti con germogli di bambù, mandorle pelate e avvolti in una deliziosa cremina insaporita con salsa di soia',
                'type' => 'Secondo',
                'price' => 7,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Pollo fritto',
                'ingredients' => 'Petto di pollo, pangrattato , uova',
                'description' => 'Bocconcini di pollo fritto, accompagnati con salsa Ketchup',
                'type' => 'Secondo',
                'price' => 7,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Pollo in salsa agrodolce',
                'ingredients' => 'Petto di pollo, pangrattato , salsa agrodolce',
                'description' => 'Bocconcini di pollo fritto, conditi con salsa agrodolce',
                'type' => 'Secondo',
                'price' => 7.5,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Anatra con arance',
                'ingredients' => 'Anatra, arance',
                'description' => 'Anatra cotta al vapore, condita con salsa di arance',
                'type' => 'Secondo',
                'price' => 8,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Manzo con funghi e bambu',
                'ingredients' => 'Manzo, funghi, germogli di bambu, ',
                'description' => 'Bocconcini di manzo, conditi con funghi cotti e germogli di bambu',
                'type' => 'Secondo',
                'price' => 8,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Gelato fritto',
                'ingredients' => 'Gelato, pangrattato, crema',
                'description' => 'Sfera di gelato alla crema fritto',
                'type' => 'Dolce',
                'price' => 3,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Involtino al cocco',
                'ingredients' => 'Sfoglia, nutella, cocco',
                'description' => 'Sfoglia farcita con Nutella® e scaglie di cocco',
                'type' => 'Dolce',
                'price' => 3,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Pandolce cinese al vapore',
                'ingredients' => 'Pane',
                'description' => 'Panini cinesi al vapore dall’aspetto candido e dalla consistenza soffice',
                'type' => 'Dolce',
                'price' => 3,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Mooncake cinese',
                'ingredients' => 'Farina, golden Syrup, uova, marmellata di fagioli Azuki ',
                'description' => ' Dolcetti di sfoglia croccante ripieno con uova e marmellata di fagioli Azuki',
                'type' => 'Dolce',
                'price' => 3,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Palline al sesamo',
                'ingredients' => 'Farina di riso dolce, zucchero,  pasta di fagioli rossi',
                'description' => ' Dolce cinese chiamato anche Jian Dui, farcito con mochi fritti e marmellata di fagioli dolci',
                'type' => 'Dolce',
                'price' => 3,
                'availability'  => true,
                'restaurant_id' => 3,
            ],

            
            
            [
                'name' => 'Uramaki di salmone',
                'ingredients' => 'Riso , alga nori , salmone , avocado ',
                'description' => 'Uramaki di salmone classico',
                'type' => 'Primo',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 17,
            ],
            [
                'name' => 'Margherita',
                'ingredients' => 'Pomodoro , Mozzarella , Basilico ',
                'description' => 'La regina delle pizze',
                'type' => 'Primo',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 16,
            ],
            [
                'name' => 'Hamburger con Patatine',
                'ingredients' => 'Pane , Hamburger , Cheddar , salse ',
                'description' => 'Hamburger di Fassona con cheddar e salsa a piacere, contorno di patatine country',
                'type' => 'Secondo',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 15,
            ],
            [
                'name' => 'Tacos della casa',
                'ingredients' => 'Tacos , Salsiccia , Peperoni , Paprika dolce ',
                'description' => 'Tacos tradizionali messicane',
                'type' => 'Antipasto',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 14,
            ],
            [
                'name' => 'Pollo al curry',
                'ingredients' => 'Pollo , Curry , Senape',
                'description' => 'Pollo al curry con riso bianco',
                'type' => 'Secondo',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 13,
            ],
            [
                'name' => 'Lasange alla bolognese',
                'ingredients' => 'Pasta , Ragù , Besciamella ',
                'description' => 'Lasagna alla bolognese classica',
                'type' => 'Primo',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 12,
            ],
            [
                'name' => 'Samosa',
                'ingredients' => 'Patate , formaggio , manzo , cipolle ',
                'description' => "piatto indiano diffuso e amato in tutta l'India, è un antipasto croccante e sfizioso.",
                'type' => 'Antipasto',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 11,
            ],
            [
                'name' => 'Panino New York',
                'ingredients' => 'Salsiccia , porchetta di Ariccia , provola , funghi e salsa',
                'description' => 'Il nostro panino della casa',
                'type' => 'Secondo',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 10,
            ],
            [
                'name' => 'Bufala e Pomodorini',
                'ingredients' => 'Pomodoro , Mozzarella di Bufala DOP, Basilico , pomodorini',
                'description' => 'Pizza estiva con Bufala e Pomodorini , un classico della cucina italiana' ,
                'type' => 'Primo',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 9,
            ],
            [
                'name' => 'Tonno in crosta di pistacchi',
                'ingredients' => 'Tonno , Pistacchi , Limone',
                'description' => 'Tonno in crosta di pistacchi con contorno di verdure grigliate',
                'type' => 'Secondo',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 8,
            ],
            [
                'name' => 'Tartar di salmone',
                'ingredients' => 'Salmone , Semi di sesamo , Salsa Guacamole ',
                'description' => 'Tartar di salmone tagliata al coltello su un letto di guacamole',
                'type' => 'Antipasto',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 7,
            ],
            [
                'name' => 'Tagliere di salumi e formaggi',
                'ingredients' => 'Salumi della casa , formaggi nostrani',
                'description' => 'I nostri salumi e formaggi a KM 0 accompagnate da maramellate miste',
                'type' => 'Antipasto',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 6,
            ],
            [
                'name' => 'Spaghetti al pomodoro',
                'ingredients' => 'Pasta , Salsa di pomodoro , Basilico ',
                'description' => 'Un primo piatto per adulti e bambini',
                'type' => 'Primo',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 5,
            ],
            [
                'name' => 'Melanzane alla parmigiana',
                'ingredients' => 'Melanzane , Mozzarella , Pomodoro ',
                'description' => 'Melanzane alla parmigiana come da ricetta casalinga',
                'type' => 'Secondo',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 4,
            ],
            [
                'name' => 'Souvlaky',
                'ingredients' => 'Polpa di agnello , Lardo di maiale , limone',
                'description' => 'Spiedini di agnello alla greca con contorno di patate e salsa allo yogurt greco',
                'type' => 'Secondo',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 3,
            ],
            [
                'name' => 'Orecchia di elefante',
                'ingredients' => 'Lonza di maiale , sale grosso , rucola , pomodorini',
                'description' => 'Cotoletta di maiale con contorno di patatine fritte',
                'type' => 'Secondo',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 4,
            ],
            [
                'name' => 'Ravioloni ripieni di polpo e burrata',
                'ingredients' => 'Ravioli , polpo , burrata ',
                'description' => 'Ravioli fatti in casa con ripieno di polpo e burrata DOP',
                'type' => 'Primo',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 4,
            ],
            [
                'name' => 'Chicken Burger',
                'ingredients' => 'Pollo , Cheddar , Salse a piacere , verdure grigiate ',
                'description' => 'Hamburger di pollo con formaggio Cheddar e contorno di patatine',
                'type' => 'Secondo',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 4,
            ],
            [
                'name' => 'Branzino alla mediterranea',
                'ingredients' => 'Branzino , pomodorini , olive taggiasche ',
                'description' => 'Branzino sfumato al vino bianco con pomodorini ed olive taggiasche, contorno di verdure miste',
                'type' => 'Secondo',
                'price' => mt_rand(1 * 2, 40 * 2) / 2,
                'availability'  => true,
                'restaurant_id' => 4,
            ],
        ];

        foreach ($products as $key => $product) {
            DB::table('products')->insert($product);
        }
    }
}

